Task
Given an integer, , perform the following conditional actions:

If  is odd, print Weird
If  is even and in the inclusive range of  to , print Not Weird
If  is even and in the inclusive range of  to , print Weird
If  is even and greater than , print Not Weird
Input Format

A single line containing a positive integer, .

Constraints

Output Format

Print Weird if the number is weird. Otherwise, print Not Weird.

In [2]:

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())

def check_weird(n):
    if n % 2 != 0:
        print("Weird")
    elif n % 2 == 0 and 2 <= n <= 5:
        print("Not Weird")
    elif n % 2 == 0 and 6 <= n <= 20:
        print("Weird")
    elif n % 2 == 0 and n > 20:
        print("Not Weird")
        
check_weird(n)

Weird


Task
The provided code stub reads and integer, , from STDIN. For all non-negative integers , print .

Example

The list of non-negative integers that are less than  is . Print the square of each number on a separate line.

0
1
4
Input Format

The first and only line contains the integer, .

Constraints


Output Format

Print  lines, one corresponding to each .

In [4]:

n = int(input())
for i in range(n):
    print(i*i)

0
1
4


An extra day is added to the calendar almost every four years as February 29, and the day is called a leap day. It corrects the calendar for the fact that our planet takes approximately 365.25 days to orbit the sun. A leap year contains a leap day.

In the Gregorian calendar, three conditions are used to identify leap years:

The year can be evenly divided by 4, is a leap year, unless:
The year can be evenly divided by 100, it is NOT a leap year, unless:
The year is also evenly divisible by 400. Then it is a leap year.
This means that in the Gregorian calendar, the years 2000 and 2400 are leap years, while 1800, 1900, 2100, 2200, 2300 and 2500 are NOT leap years. Source

Task

Given a year, determine whether it is a leap year. If it is a leap year, return the Boolean True, otherwise return False.

Note that the code stub provided reads from STDIN and passes arguments to the is_leap function. It is only necessary to complete the is_leap function.

In [6]:
def is_leap(year):
    leap = False
    
    # Write your logic here
    if (year%4==0 and year%100 !=0) or (year%400==0):
        leap=True
    return leap

year = int(input())
print(is_leap(year))

True


The included code stub will read an integer, , from STDIN.

Without using any string methods, try to print the following:


Note that "" represents the consecutive values in between.

Example

Print the string .

Input Format

The first line contains an integer .

Constraints


Output Format

Print the list of integers from  through  as a string, without spaces.

In [7]:
n = int(input())
for i in range(1,n+1):
    print(i,end='')

1234

Task

You are given two integer arrays of size X and X ( &  are rows, and  is the column). Your task is to concatenate the arrays along axis .

Input Format

The first line contains space separated integers ,  and .
The next  lines contains the space separated elements of the  columns.
After that, the next  lines contains the space separated elements of the  columns.

Output Format

Print the concatenated array of size X.
Print the concatenated array of size X.

Task

You are given two integer arrays of size X and X ( &  are rows, and  is the column). Your task is to concatenate the arrays along axis .

Input Format

The first line contains space separated integers ,  and .
The next  lines contains the space separated elements of the  columns.
After that, the next  lines contains the space separated elements of the  columns.

Output Format

Print the concatenated array of size X.

Sample Input

4 3 2
1 2
1 2 
1 2
1 2
3 4
3 4
3 4 
Sample Output

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 
Language
Python 3
More
1234567891011121314151617181920

# Concatenating along axis 0
result = np.concatenate((array1, array2), axis=0)

# Printing the result
print(result)







Line: 17 Col: 1

Test against custom input
Python
You have earned 20.00 points!
You are now 15 points away from the 3rd star for your python badge.
63%95/110
Congratulations
You solved this challenge. Would you like to challenge your friends?Share on FacebookShare on TwitterShare on LinkedIn

Test case 0

Test case 1

Test case 2
Compiler Message
Success
Input (stdin)
4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
Expected Output
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [ ]:
import numpy as np

# Reading the first line containing n, m, p
n, m, p = map(int, input().strip().split())

# Reading the next n lines into the first array
array1 = np.array([input().strip().split() for _ in range(n)], int)

# Reading the next m lines into the second array
array2 = np.array([input().strip().split() for _ in range(m)], int)

# Concatenating along axis 0
result = np.concatenate((array1, array2), axis=0)

# Printing the result
print(result)


Task

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

Input Format

A single line containing the space-separated integers.

Constraints


Output Format

First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.

In [15]:
import numpy as np

# Reading the input and converting it to a tuple of integers
shape = tuple(map(int, input().strip().split()))

# Creating an array of zeros with the given shape
zeros_array = np.zeros(shape, dtype=int)
print(zeros_array)

# Creating an array of ones with the given shape
ones_array = np.ones(shape, dtype=int)
print(ones_array)


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]


Let's learn about list comprehensions! You are given three integers  and  representing the dimensions of a cuboid along with an integer . Print a list of all possible coordinates given by  on a 3D grid where the sum of  is not equal to . Here, . Please use list comprehensions rather than multiple loops, as a learning exercise.

Example




All permutations of  are:
.

Print an array of the elements that do not sum to .


Input Format

Four integers  and , each on a separate line.

Constraints

Print the list in lexicographic increasing order.

Sample Input 0

1
1
1
2
Sample Output 0

[[0, 0, 0], [0, 0, 1], [0, 1, 0], [1, 0, 0], [1, 1, 1]]
Explanation 0

Each variable  and  will have values of  or . All permutations of lists in the form .
Remove all arrays that sum to  to leave only the valid permutations.

Sample Input 1

2
2
2
2
Sample Output 1

[[0, 0, 0], [0, 0, 1], [0, 1, 0], [0, 1, 2], [0, 2, 1], [0, 2, 2], [1, 0, 0], [1, 0, 2], [1, 1, 1], [1, 1, 2], [1, 2

In [2]:

x = int(input())
y = int(input())
z = int(input())
n = int(input())
    
result=[[i,j,k] for i in range(x+1)
                for j in range(y+1)
                for k in range(z+1)
                if i+j+k != n]
                
print(result)

[[0, 0, 0], [0, 0, 1], [0, 0, 2], [0, 1, 0], [0, 1, 1], [0, 1, 3], [0, 2, 0], [0, 2, 2], [0, 2, 3], [0, 3, 1], [0, 3, 2], [0, 3, 3], [1, 0, 0], [1, 0, 1], [1, 0, 3], [1, 1, 0], [1, 1, 2], [1, 1, 3], [1, 2, 1], [1, 2, 2], [1, 2, 3], [1, 3, 0], [1, 3, 1], [1, 3, 2], [1, 3, 3], [2, 0, 0], [2, 0, 2], [2, 0, 3], [2, 1, 1], [2, 1, 2], [2, 1, 3], [2, 2, 0], [2, 2, 1], [2, 2, 2], [2, 2, 3], [2, 3, 0], [2, 3, 1], [2, 3, 2], [2, 3, 3], [3, 0, 1], [3, 0, 2], [3, 0, 3], [3, 1, 0], [3, 1, 1], [3, 1, 2], [3, 1, 3], [3, 2, 0], [3, 2, 1], [3, 2, 2], [3, 2, 3], [3, 3, 0], [3, 3, 1], [3, 3, 2], [3, 3, 3]]


Input Format

The first line contains . The second line contains an array   of  integers each separated by a space.

Constraints

Output Format

Print the runner-up score.

Sample Input 0

5
2 3 6 6 5
Sample Output 0

5
Explanation 0

Given list is . The maximum score is , second maximum is . Hence, we print  as the runner-up score.

In [3]:
n = int(input())
arr = map(int, input().split())
    
unique_score=sorted(set(arr),reverse=True)

runner_up_score=unique_score[1]

print(runner_up_score)

8


Given 2 numbers N,K followed by a sorted array of N elements, search and tell if an element K is present in the array.print 'yes' if element is present otherwise print 'no'.
Input Size : 1 <= N <= 1000000000000000(Do it in logN time complexity)
Sample Testcase :
INPUT
3 2
2 3 7
OUTPUT
Yes

In [4]:
def binary_search(arr, k):
    left, right = 0, len(arr) - 1
    while left <= right:
        mid = (left + right) // 2
        if arr[mid] == k:
            return "yes"
        elif arr[mid] < k:
            left = mid + 1
        else:
            right = mid - 1
    return "no"

# Input the size of the array and the element to search for
N, K = map(int, input().split())

# Input the array of elements
arr = list(map(int, input().split()))

# Apply binary search and print the result
result = binary_search(arr, K)
print(result)


no


Given a number N and an array of N elements,sort the array in increasing order and print the original indices of the elements present in sorted array.
Input Size : N <= 100000
Sample Testcase :
INPUT
5
5 4 3 2 1
OUTPUT
5 4 3 2 1

In [5]:
# Input the number of elements
N = int(input())

# Input the array of elements
arr = list(map(int, input().split()))

# Pair each element with its original index (0-based index)
indexed_arr = [(value, index) for index, value in enumerate(arr)]

# Sort the array based on the values
indexed_arr.sort()

# Extract the original indices after sorting
result = [index + 1 for value, index in indexed_arr]  # Keep the 1-based index

# Print the result
print(" ".join(map(str, result)))


1 2 3 4 5


Given a number N, followed by an array of N elements,print 'yes' if it is a sorted array(either ascending or descending)otherwise print 'no'.
Input Size : 1 <= N <= 100000
Sample Testcase :
INPUT
3
2 3 7
OUTPUT
yes

In [6]:
N=int(input())

arr=list(map(int,input().split()))

def is_sorted(arr):
    ascending=True
    descending=True
    
    for i in range(1,N):
        if arr[i]<arr[i-1]:
            ascending=False
        if arr[i]>arr[i-1]:
            descending=False
            
    return ascending or descending

if is_sorted(arr):
    print("yes")
else:
    print("no")

yes


Given an array of N strings sort it in ascending order based on the length of the string.If two strings are found to have the same length sort them in lexicographical order.
Sample Testcase :
INPUT
3
coding platform codekata
OUTPUT
coding codekata platform

In [7]:
N=int(input())

string=input().split()

string.sort(key=lambda x:(len(x),x))

print(" ".join(string))

coding codekata platform


Given 3 points check whether they lie on the same line.If they lie on the same line print 'yes' Otherwise print 'no'.
Sample Testcase :
INPUT
0 1
0 0
0 2
OUTPUT
yes

In [8]:
x1,y1=map(int,input().split())
x2,y2=map(int,input().split())
x3,y3=map(int,input().split())

if (y2-y1)*(x3-x2) == (y3-y2)*(x2-x1):
    print("yes")
else:
    print("no")

yes


You are given a number N and followed by an array of N numbers and followed by two elements U and V, find the minimum distance between the elements in the array. The array may have duplicates.
For example, if the array is (1, 5, 3, 7, 2, 8, 3, 4, 5, 9, 9, 3, 1, 3, 2, 9)
Min Distance (U=4, V= 7): 4
Input Size : N <= 100000
Sample Testcase :
INPUT
16
1 5 3 7 2 8 3 4 5 9 9 3 1 3 2 9
4 7
OUTPUT
4

In [ ]:
def min_distance(arr, U, V):
    # Initialize variables to keep track of the last seen positions and minimum distance
    last_U = -1
    last_V = -1
    min_dist = float('inf')
    
    # Traverse the array
    for i in range(len(arr)):
        if arr[i] == U:
            if last_V != -1:
                min_dist = min(min_dist, i - last_V)
            last_U = i
        elif arr[i] == V:
            if last_U != -1:
                min_dist = min(min_dist, i - last_U)
            last_V = i
    
    return min_dist

# Input reading
N = int(input())
arr = list(map(int, input().split()))
U, V = map(int, input().split())

# Calculate the minimum distance
result = min_distance(arr, U, V)

# Print the result
print(result)


Maxwell wants to buy an apartment in a new house at Line Avenue of Metropolis. The house has n apartments that are numbered from 1 to n and are arranged in a row. Two apartments are adjacent if their indices differ by 1. Some of the apartments can already be inhabited, others are available for sale. Maxwell often visits his neighbors, so apartment is good for him if it is available for sale and there is at least one already inhabited apartment adjacent to it. Maxwell knows that there are exactly k already inhabited apartments, but he doesn't know their indices yet. Find out what could be the minimum possible and the maximum possible number of apartments that are good for Maxwell.
Input Size : N<=K<=1000000000
Example:
INPUT
6 3
OUTPUT
1 3

In [10]:
def min_max_good_apartments(n, k):
    if n == k:
        # If all apartments are inhabited, no apartment can be good
        return 0, 0
    
    # Calculate maximum number of good apartments
    max_good = min(n - k, 2 * k)
    
    # Calculate minimum number of good apartments
    min_good = max(0, k - 1)
    
    return min_good, max_good

# Read input
n, k = map(int, input().split())

# Compute result
result = min_max_good_apartments(n, k)

# Print result
print(result[0], result[1])


2 3


Alternate sorting:Given a number N followed by array of N elements,sort the array in such a way that the first number is the first maximum and second number is the 1st minimum 3rd number isthe 2nd maximum and so on.
Input Size : N <= 100000
Sample Testcase :
INPUT
8
7 623 19 10 11 9 3 15
OUTPUT
623 3 19 7 15 9 11 10

In [ ]:
def alternate_sort(N, array):
    # Sort the array
    sorted_array = sorted(array)
    
    # Create result list
    result = []
    
    # Initialize pointers for min and max elements
    left = 0
    right = N - 1
    
    # Alternate between picking from the end and the start
    while left <= right:
        if left <= right:
            result.append(sorted_array[right])
            right -= 1
        if left <= right:
            result.append(sorted_array[left])
            left += 1
    
    # Print the result
    print(" ".join(map(str, result)))

# Read input values
N = int(input())
array = list(map(int, input().split()))

# Compute and output the alternate sorted array
alternate_sort(N, array)
