Task
Given an integer, , perform the following conditional actions:

If  is odd, print Weird
If  is even and in the inclusive range of  to , print Not Weird
If  is even and in the inclusive range of  to , print Weird
If  is even and greater than , print Not Weird
Input Format

A single line containing a positive integer, .

Constraints

Output Format

Print Weird if the number is weird. Otherwise, print Not Weird.

In [2]:

import math
import os
import random
import re
import sys



if __name__ == '__main__':
    n = int(input().strip())

def check_weird(n):
    if n % 2 != 0:
        print("Weird")
    elif n % 2 == 0 and 2 <= n <= 5:
        print("Not Weird")
    elif n % 2 == 0 and 6 <= n <= 20:
        print("Weird")
    elif n % 2 == 0 and n > 20:
        print("Not Weird")
        
check_weird(n)

Weird


Task
The provided code stub reads and integer, , from STDIN. For all non-negative integers , print .

Example

The list of non-negative integers that are less than  is . Print the square of each number on a separate line.

0
1
4
Input Format

The first and only line contains the integer, .

Constraints


Output Format

Print  lines, one corresponding to each .

In [4]:

n = int(input())
for i in range(n):
    print(i*i)

0
1
4


An extra day is added to the calendar almost every four years as February 29, and the day is called a leap day. It corrects the calendar for the fact that our planet takes approximately 365.25 days to orbit the sun. A leap year contains a leap day.

In the Gregorian calendar, three conditions are used to identify leap years:

The year can be evenly divided by 4, is a leap year, unless:
The year can be evenly divided by 100, it is NOT a leap year, unless:
The year is also evenly divisible by 400. Then it is a leap year.
This means that in the Gregorian calendar, the years 2000 and 2400 are leap years, while 1800, 1900, 2100, 2200, 2300 and 2500 are NOT leap years. Source

Task

Given a year, determine whether it is a leap year. If it is a leap year, return the Boolean True, otherwise return False.

Note that the code stub provided reads from STDIN and passes arguments to the is_leap function. It is only necessary to complete the is_leap function.

In [6]:
def is_leap(year):
    leap = False
    
    # Write your logic here
    if (year%4==0 and year%100 !=0) or (year%400==0):
        leap=True
    return leap

year = int(input())
print(is_leap(year))

True


The included code stub will read an integer, , from STDIN.

Without using any string methods, try to print the following:


Note that "" represents the consecutive values in between.

Example

Print the string .

Input Format

The first line contains an integer .

Constraints


Output Format

Print the list of integers from  through  as a string, without spaces.

In [7]:
n = int(input())
for i in range(1,n+1):
    print(i,end='')

1234

Task

You are given two integer arrays of size X and X ( &  are rows, and  is the column). Your task is to concatenate the arrays along axis .

Input Format

The first line contains space separated integers ,  and .
The next  lines contains the space separated elements of the  columns.
After that, the next  lines contains the space separated elements of the  columns.

Output Format

Print the concatenated array of size X.
Print the concatenated array of size X.

Task

You are given two integer arrays of size X and X ( &  are rows, and  is the column). Your task is to concatenate the arrays along axis .

Input Format

The first line contains space separated integers ,  and .
The next  lines contains the space separated elements of the  columns.
After that, the next  lines contains the space separated elements of the  columns.

Output Format

Print the concatenated array of size X.

Sample Input

4 3 2
1 2
1 2 
1 2
1 2
3 4
3 4
3 4 
Sample Output

[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]] 
Language
Python 3
More
1234567891011121314151617181920

# Concatenating along axis 0
result = np.concatenate((array1, array2), axis=0)

# Printing the result
print(result)







Line: 17 Col: 1

Test against custom input
Python
You have earned 20.00 points!
You are now 15 points away from the 3rd star for your python badge.
63%95/110
Congratulations
You solved this challenge. Would you like to challenge your friends?Share on FacebookShare on TwitterShare on LinkedIn

Test case 0

Test case 1

Test case 2
Compiler Message
Success
Input (stdin)
4 3 2
1 2
1 2
1 2
1 2
3 4
3 4
3 4
Expected Output
[[1 2]
 [1 2]
 [1 2]
 [1 2]
 [3 4]
 [3 4]
 [3 4]]


In [ ]:
import numpy as np

# Reading the first line containing n, m, p
n, m, p = map(int, input().strip().split())

# Reading the next n lines into the first array
array1 = np.array([input().strip().split() for _ in range(n)], int)

# Reading the next m lines into the second array
array2 = np.array([input().strip().split() for _ in range(m)], int)

# Concatenating along axis 0
result = np.concatenate((array1, array2), axis=0)

# Printing the result
print(result)


Task

You are given the shape of the array in the form of space-separated integers, each integer representing the size of different dimensions, your task is to print an array of the given shape and integer type using the tools numpy.zeros and numpy.ones.

Input Format

A single line containing the space-separated integers.

Constraints


Output Format

First, print the array using the numpy.zeros tool and then print the array with the numpy.ones tool.

In [15]:
import numpy as np

# Reading the input and converting it to a tuple of integers
shape = tuple(map(int, input().strip().split()))

# Creating an array of zeros with the given shape
zeros_array = np.zeros(shape, dtype=int)
print(zeros_array)

# Creating an array of ones with the given shape
ones_array = np.ones(shape, dtype=int)
print(ones_array)


[[[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]
  [0 0 0]]]
[[[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]]]
